// All collections actions
export const SAVE_ALL_STORIES = "SAVE_ALL_STORIES";

// User actions
export const USER_LOGIN_SUCCESSFUL = "USER_LOGIN_SUCCESSFUL";
export const SET_USER_TOKEN = "SET_USER_TOKEN";
export const REMOVE_USER_TOKEN = "REMOVE_USER_TOKEN";
export const REMOVE_LIKED_STORY = "REMOVE_LIKED_STORY";
export const REMOVE_BOOKMARKED_STORY = "REMOVE_BOOKMARKED_STORY";
export const ADD_LIKED_STORY = "ADD_LIKED_STORY";
export const ADD_BOOKMARKED_STORY = "ADD_BOOKMARKED_STORY";

// Story actions
export const SAVE_STORY_DETAILS = "SAVE_STORY_DETAILS";
export const SAVE_ALL_TAGS = "SAVE_ALL_TAGS";
export const SAVE_RESPONSE = "SAVE_RESPONSE";
export const RESET_STORY_REDUCER = "RESET_STORY_REDUCER";

// Question actions
export const SAVE_ALL_QUESTION = "SAVE_ALL_QUESTIONS";
export const INCREMENT_QUESTION_INDEX = "INCREMENT_QUESTION_INDEX";
export const DECREMENT_QUESTION_INDEX = 'DECREMENT_QUESTION_INDEX';
export const INCREMENT_SUB_QUESTION_INDEX = "INCREMENT_SUB_QUESTION_INDEX";
export const DECREMENT_SUB_QUESTION_INDEX = 'DECREMENT_SUB_QUESTION_INDEX';
export const SET_SUB_QUESTION_ACTIVE_TRUE = "SET_SUB_QUESTION_ACTIVE_TRUE";
export const SET_SUB_QUESTION_ACTIVE_FALSE = "SET_SUB_QUESTION_ACTIVE_FALSE";
export const SAVE_SUB_QUESTION = 'SET_SUB_QUESTION';
export const RESET_SUB_QUESTION_INDEX = 'RESET_SUB_QUESTION_INDEX';
export const RESET_QUESTION_INDEX = 'RESET_QUESTION_INDEX';
export const RESET_ALL_BUT_QUESTIONS = 'RESET_ALL_BUT_QUESTIONS';
export const RESET_QUESTION_REDUCER_TO_ORIGINAL_STATE = "RESET_QUESTION_INDEX";

// Recorder actions
export const PLAYER_STATE = "PLAYER_STATE";
export const RESET_RECORDER_STATE = "RESET_RECORDER_STATE";
export const SET_RECORDED_AUDIO_FILEPATH = "SET_RECORDED_AUDIO_FILEPATH";

// Audio player actions


